name: zad2
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag"
        default: "default"
jobs:
  dockerCI:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: adamos321/zad2:${{ github.event.inputs.tag }}
        
  kubernetesCI:
    needs: dockerCI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: AdamPiechowiak/zad2-config-repo
          token: ${{ secrets.ACTIONS_TOKEN }}
      - run: |
          sed -i 's/adamos321\/zad2:.*/adamos321\/zad2:${{ github.event.inputs.tag }}/g' my-app-deploy.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -u
          git commit -m "updated app version ${{ github.event.inputs.tag }}"
          git push
